DROP DATABASE IF EXISTS SONGDB;

CREATE DATABASE SONGDB;

use SONGDB;

CREATE TABLE USER(
    USER_ID int NOT NULL AUTO_INCREMENT,
    USER_EMAIL varchar(255) UNIQUE NOT NULL,
    USER_PASSWORD varchar(255) NOT NULL,
    PRIMARY KEY(USER_ID),
    UNIQUE(USER_EMAIL)
);

CREATE TABLE SONGS(
    SONG_ID int NOT NULL AUTO_INCREMENT,
    SONG_NAME varchar(255) NOT NULL,
    USER_ID int NOT NULL,
    PRIMARY KEY (SONG_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);

